

const ALL_SERVICES = [
    SERVICE_EC2, SERVICE_S3, SERVICE_RDS, SERVICE_DYNAMODB, SERVICE_LAMBDA,
    SERVICE_ELB, SERVICE_ECS, SERVICE_SNS, SERVICE_SQS, SERVICE_EKS,
    SERVICE_EFS, SERVICE_ELASTICACHE, SERVICE_REDSHIFT, SERVICE_OPENSEARCH,
    SERVICE_FSX, SERVICE_MSK, SERVICE_EMR, SERVICE_KINESIS, SERVICE_FIREHOSE,
    SERVICE_MQ, SERVICE_ECR, SERVICE_APIGATEWAY, SERVICE_GLUE, SERVICE_STEPFUNCTIONS,
    SERVICE_KMS, SERVICE_SECRETSMANAGER, SERVICE_SAGEMAKER, SERVICE_CLOUDFRONT,
    SERVICE_DMS, SERVICE_NETWORKFIREWALL, SERVICE_TRANSFER,
    SERVICE_WORKSPACES, SERVICE_TIMESTREAM, SERVICE_DATASYNC, SERVICE_ROUTE53,
    SERVICE_STORAGEGATEWAY, SERVICE_MEMORYDB, SERVICE_KEYSPACES, SERVICE_APPSTREAM,
    SERVICE_DS, SERVICE_ACM, SERVICE_APPSYNC, SERVICE_CODEBUILD, SERVICE_CODEPIPELINE,
    SERVICE_BACKUP, SERVICE_LOGS, SERVICE_COGNITO_IDP, SERVICE_COGNITO_IDENTITY,
    SERVICE_KINESISANALYTICS, SERVICE_GAMELIFT, SERVICE_KENDRA, SERVICE_MEDIACONVERT,
    SERVICE_MEDIALIVE, SERVICE_MEDIAPACKAGE, SERVICE_M2, SERVICE_RESILIENCEHUB,
    SERVICE_FINSPACE, SERVICE_OMICS, SERVICE_REDSHIFT_SERVERLESS, SERVICE_COMPREHEND,
    SERVICE_DIRECTCONNECT, SERVICE_CLOUDHSM, SERVICE_GLACIER,
    SERVICE_BEDROCK, SERVICE_BEDROCK_AGENT, SERVICE_QUICKSIGHT,
    SERVICE_SECURITYHUB, SERVICE_ATHENA, SERVICE_SERVICECATALOG, SERVICE_RAM,
    SERVICE_ACMPCA, SERVICE_AOSS, SERVICE_KINESISVIDEO, SERVICE_DSQL,
    SERVICE_VPCLATTICE, SERVICE_BEDROCK_AGENTCORE, SERVICE_PAYMENTCRYPTOGRAPHY,
    SERVICE_NETWORKMANAGER, SERVICE_WORKSPACES_INSTANCES,
    SERVICE_DAX, SERVICE_DRS, SERVICE_DEADLINE, SERVICE_IOT,
    SERVICE_WAFV2, SERVICE_CODEDEPLOY,
];

const ALL_EVENT_NAMES = [
    ...SHARED_EVENTS,
    ...ALL_SERVICES.flatMap(s => s.events),
];

const ALL_SOURCES = ALL_SERVICES.map(s => s.source);

const TAGGING_PERMISSIONS = [
    ...SHARED_PERMISSIONS,
    ...ALL_SERVICES.flatMap(s => s.permissions),
];

